[package]
name = "discord-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
image = "0.24.8"
jemini = { path = "../../" }
log = "0.4.20"
once_cell = "1.19.0"
poise = "0.6.1"
pretty_env_logger = "0.5.0"
tokio = { version = "1.36.0", features = ["full"] }
